"""new fields in user model

Revision ID: 7873adba363a
Revises: 8c45dbb3aa79
Create Date: 2018-03-22 19:23:41.502423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7873adba363a'
down_revision = '8c45dbb3aa79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
